#!/usr/bin/env python3

import mysql.connector

# Comprehensive list of Indian stock symbols
symbols_data = {
    "Moser Baer India Ltd.": "MOSERBAER",
    "Mazda Ltd.": "MAZDA",
    "Medi-Caps Ltd.": "MEDICAPSBE",
    "Muthoot Capital Services Ltd.": "MUTHOOTCAP",
    "Mahindra Ugine Steel Company Ltd.": "MAHINDUGIN",
    "McLeod Russel (India) Ltd.": "MCLEODRUSS",
    "Mylan Laboratories Ltd.": "MATRIXLABS",
    "McNally Bharat Engineering Company Ltd.": "MBECL",
    "MT Educare Ltd.": "MTEDUCARE",
    "Mahanagar Telephone Nigam Ltd.": "MTNL",
    "Metkore Alloys & Industries Ltd.": "METKOREBE",
    "Madhav Marbles & Granites Ltd.": "MADHAV",
    "Maan Aluminium Ltd.": "MAANALU",
    "Maars Software International Ltd.": "MAARSOFTWBE",
    "Max Ventures and Industries Ltd.": "MAXVIL",
    "Motor & General Finance Ltd.": "MOTOGENFINBE",
    "Mahendra Petrochemicals Ltd.": "MAHENDSUITBE",
    "Marico Kaya Enterprises Ltd.": "MAKE",
    "Malwa Cotton Spinning Mills Ltd.": "MALWACOTTBE",
    "Manaksia Aluminium Company Ltd.": "MANAKALUCOBE",
    "Monsanto India Ltd.": "MONSANTO",
    "Modipon Ltd.": "MODIPONBE",
    "Magnum Ventures Ltd.": "MAGNUM",
    "Marico Ltd.": "MARICO",
    "MPL Plastics Ltd.": "MILTONPLAS",
    "Manappuram Finance Ltd.": "MANAPPURAM",
    "Mirza International Ltd.": "MIRZAINT",
    "Mold-Tek Packaging Ltd.": "MOLDTKPAC",
    "MIRC Electronics Ltd.": "MIRCELECTR",
    "M M Forgings Ltd.": "MMFL",
    "Manaksia Steels Ltd.": "MANAKSTEEL",
    "MphasiS Ltd.": "MPHASIS",
    "Man Infraconstruction Ltd.": "MANINFRA",
    "Mangalore Chemicals & Fertilizers Ltd.": "MANGCHEFER",
    "Mercator Ltd.": "MERCATOR",
    "MRO-TEK Realty Ltd.": "MRO-TEK",
    "M R Organisation Ltd.": "MROIT",
    "Madras Aluminium Company Ltd.": "MALCO",
    "Murudeshwar Ceramics Ltd.": "MURUDCERA",
    "Max India Ltd.": "MAXINDIA",
    "Maharashtra Seamless Ltd.": "MAHSEAMLES",
    "Maruti Suzuki India Ltd.": "MARUTI",
    "Motherson Sumi Systems Ltd.": "MOTHERSUMI",
    "MIG Media Neurons Ltd.": "MMNLIT",
    "Manglam Timber Products Ltd.": "MANGTIMBER",
    "Monica Electronics Ltd.": "MONICAELECBE",
    "Maral Overseas Ltd.": "MARALOVER",
    "Mastek Ltd.": "MASTEK",
    "Minda Industries Ltd.": "MINDAIND",
    "MVL Ltd.": "MVL",
    "Mindteck (India) Ltd.": "MINDTECK",
    "Modern Insulators Ltd.": "MODINSULATBE",
    "Manali Petrochemicals Ltd.": "MANALIPETC",
    "Marathon Nextgen Realty Ltd.": "MARATHON",
    "Mahamaya Steel Industries Ltd.": "MAHASTEEL",
    "Mafatlal Industries Ltd.": "MAFATLAINDBE",
    "Mahanagar Gas Ltd.": "MGL",
    "Mold-Tek Technologies Ltd.": "MOLDTECH",
    "Manjushree Technopack Ltd.": "MANJUSHREE",
    "Megasoft Ltd.": "MEGASOFT",
    "Mangalam Drugs and Organics Ltd.": "MANGALAM",
    "MPS Ltd.": "MPSLTD",
    "Melstar Information Technology Ltd.": "MELSTAR",
    "Madhucon Projects Ltd.": "MADHUCON",
    "Manpasand Beverages Ltd.": "MANPASAND",
    "MOIL Ltd.": "MOIL",
    "MindTree Ltd.": "MINDTREE",
    "Magma Fincorp Ltd.": "MAGMA",
    "Mawana Sugars Ltd.": "MAWANASUG",
    "Morarjee Textiles Ltd.": "MORARJEE",
    "Mahindra Lifespace Developers Ltd.": "MAHLIFE",
    "Media Matrix Worldwide Ltd.": "MMWL",
    "Morepen Laboratories Ltd.": "MOREPENLAB",
    "Manaksia Ltd.": "MANAKSIA",
    "Mayur Uniquoters Ltd.": "MAYURUNIQ",
    "Mysore Petro Chemicals Ltd.": "MYSORPETROBE",
    "MMTC Ltd.": "MMTC",
    "Malu Paper Mills Ltd.": "MALUPAPER",
    "Majestic Auto Ltd.": "MAJESAUTO",
    "Max Financial Services Ltd.": "MFSL",
    "Man Industries (India) Ltd.": "MANINDS",
    "Manjeera Constructions Ltd.": "MANJEERA",
    "Motilal Oswal Financial Services Ltd.": "MOTILALOFS",
    "Madras Fertilizers Ltd.": "MADRASFERT",
    "Meghmani Organics Ltd.": "MEGH",
    "Mahindra & Mahindra Financial Services Ltd.": "MandMFIN",
    "Maithan Alloys Ltd.": "MAITHANALL",
    "Munjal Showa Ltd.": "MUNJALSHOW",
    "Manugraph India Ltd.": "MANUGRAPH",
    "Marksans Pharma Ltd.": "MARKSANS",
    "Muthoot Finance Ltd.": "MUTHOOTFIN",
    "Monte Carlo Fashions Ltd.": "MONTECARLO",
    "Mahindra CIE Automotive Ltd.": "MAHINDCIE",
    "Marg Ltd.": "MARG",
    "Mukta Arts Ltd.": "MUKTAARTS",
    "Monnet Ispat & Energy Ltd.": "MONNETISPA",
    "Metalyst Forgings Ltd.": "METALFORGE",
    "Modi Rubber Ltd.": "MODIRUBBER",
    "Merck Ltd.": "MERCK",
    "Mangalore Refinery And Petrochemicals Ltd.": "MRPL",
    "Majesco Ltd.": "MAJESCO",
    "Mahindra & Mahindra Ltd.": "MandM",
    "Mangalam Cement Ltd.": "MANGLMCEM",
    "Mahindra Holidays & Resorts India Ltd.": "MHRIL",
    "Minda Corporation Ltd.": "MINDACORP",
    "Multi Commodity Exchange of India Ltd.": "MCX",
    "MRF Ltd.": "MRF",
    "Mahaveer Cotts Strings Ltd.": "MCSLIT",
    "Mukand Ltd.": "MUKANDLTD",
    "Micro Technologies (India) Ltd.": "MICROTECH",
    "Whirlpool of India Ltd.": "WHIRLPOOL",
    "Wipro Ltd.": "WIPRO",
    "Welspun Enterprises Ltd.": "WELENT",
    "Wonderla Holidays Ltd.": "WONDERLA",
    "Welspun Corp Ltd.": "WELCORP",
    "Welspun India Ltd.": "WELSPUNIND",
    "Wockhardt Ltd.": "WOCKPHARMA",
    "Honeywell Automation India Ltd.": "HONAUT",
    "Hindustan Petroleum Corporation Ltd.": "HINDPETRO",
    "Hindustan Unilever Ltd.": "HINDUNILVR",
    "Havells India Ltd.": "HAVELLS",
    "Hexaware Technologies Ltd.": "HEXAWARE",
    "HCL Technologies Ltd.": "HCLTECH",
    "HDFC Bank Ltd.": "HDFCBANK",
    "HDFC Ltd.": "HDFC",
    "Hero MotoCorp Ltd.": "HEROMOTOCO",
    "Hindustan Motors Ltd.": "HINDMOTORS",
    "HT Media Ltd.": "HTMEDIA",
    "Tech Mahindra Ltd.": "TECHM",
    "Tata Motors Ltd.": "TATAMOTORS",
    "Tata Communications Ltd.": "TATACOMM",
    "Tata Global Beverages Ltd.": "TATAGLOBAL",
    "TVS Motor Company Ltd.": "TVSMOTOR",
    "Tata Elxsi Ltd.": "TATAELXSI",
    "Triveni Engineering & Industries Ltd.": "TRIVENI",
    "Trident Ltd.": "TRIDENT",
    "Tata Consultancy Services Ltd.": "TCS",
    "Titan Company Ltd.": "TITAN",
    "Tata Steel Ltd.": "TATASTEEL",
    "Torrent Pharmaceuticals Ltd.": "TORNTPHARM",
    "Transport Corporation of India Ltd.": "TCI",
    "NTPC Ltd.": "NTPC",
    "Novartis India Ltd.": "NOVARTIND",
    "NIIT Ltd.": "NIITLTD",
    "Nestle India Ltd.": "NESTLEIND",
    "National Aluminium Company Ltd.": "NATIONALUM",
    "NIFTY 50 Index": "NIFTY50",
    "Oil India Ltd.": "OIL",
    "Oil & Natural Gas Corporation Ltd.": "ONGC",
    "Oriental Bank of Commerce": "ORIENTBANK",
    "OrientalHotels Ltd.": "ORIENTHOT",
    "Orient Refractories Ltd.": "ORIENTREF",
    "Orient Paper & Industries Ltd.": "ORIENTPPR",
    "Oracle Financial Services Software Ltd.": "OFSS",
    "Bosch Ltd.": "BOSCHLTD",
    "Bharti Airtel Ltd.": "BHARTIARTL",
    "Bharat Petroleum Corporation Ltd.": "BPCL",
    "Balkrishna Industries Ltd.": "BALKRISIND",
    "Bajaj Auto Ltd.": "BAJAJ-AUTO",
    "Bajaj Finance Ltd.": "BAJFINANCE",
    "Bajaj Finserv Ltd.": "BAJAJFINSV",
    "Britannia Industries Ltd.": "BRITANNIA",
    "Blue Star Ltd.": "BLUESTARCO",
    "Bata India Ltd.": "BATAINDIA",
    "Bank of India": "BANKINDIA",
    "Bank of Baroda": "BANKBARODA",
    "BEML Ltd.": "BEML",
    "Birla Corporation Ltd.": "BIRLACORPN",
    "Ambuja Cements Ltd.": "AMBUJACEM",
    "Axis Bank Ltd.": "AXISBANK",
    "Aditya Birla Nuvo Ltd.": "ABIRLANUVO",
    "Asian Paints Ltd.": "ASIANPAINT",
    "Ashok Leyland Ltd.": "ASHOKLEY",
}

try:
    conn = mysql.connector.connect(
        host="localhost",
        user="root",
        password="root",
        database="trading_system"
    )
    cursor = conn.cursor()
    
    # Insert all symbols (ignore duplicates using INSERT IGNORE)
    added = 0
    for company, symbol in symbols_data.items():
        try:
            cursor.execute(
                "INSERT IGNORE INTO security_master (symbol, security_type, description) VALUES (%s, %s, %s)",
                (symbol, "EQUITY", company)
            )
            if cursor.rowcount > 0:
                added += 1
        except Exception as e:
            pass
    
    conn.commit()
    
    # Verify
    cursor.execute("SELECT COUNT(*) as count FROM security_master;")
    total = cursor.fetchone()[0]
    
    cursor.close()
    conn.close()
    
    print(f"✓ Added {added} new symbols!")
    print(f"✓ Total symbols in database: {total}")
    
except Exception as e:
    print(f"✗ Error: {e}")
